### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by Shuri-Honda-1101** [Shuri-Honda-1101/todo-go#1]
# 概要
プロジェクトの開発を始めるために必要な環境構築を行う。
これには、必要なソフトウェアのインストールや設定の調整が含まれる。

# 目的
- スムーズに開発工程に移り、開発タスクへ取り掛かる。
- git操作・コマンドライン操作の初歩を学ぶ。

# タスク
- [x] githubアカウントの作成、および招待
- [x] WSL2のインストール
- [x] VScode or Cursorのインストール(もしくは何らかのエディタ)
- [x] Gitのインストール
- [x] リポジトリのクローン
- [x] goのインストール
- [x] エディタにGo拡張機能を入れる
- [x] Goの初期設定
- [x] サーバーを起動させる
- [x] gitをpullしてみる
- [x] Node.jsのインストール
- [x] クライアントを起動させる
- [x] MySQLをインストールする
- [x] データベースを作成する

# 具体的な手順
## githubアカウントの作成、および招待
割愛

## WSL2のインストール
https://qiita.com/zakoken/items/61141df6aeae9e3f8e36

## エディタのインストール
AIを使うならCursor
https://www.cursor.com/
VScodeの進化版みたいな感じ

定番ならVScode
https://code.visualstudio.com/

## Gitのインストール
~~https://qiita.com/T-H9703EnAc/items/4fbe6593d42f9a844b1c~~
https://qiita.com/studio_meowtoon/items/719e6765dd11f17a0b19

## リポジトリのクローン
作業ディレクトリを作成する
```zsh
# ルートディレクトリに移動
cd

# 開発用ディレクトリを作成(既にあれば省略)
mkdir dev

# 開発用ディレクトリに移動
cd dev
```

下記をコピーしてコマンドラインで入力する
<img width="963" alt="スクリーンショット 2024-07-31 0 04 29" src="https://github.com/user-attachments/assets/580364ea-ddd3-4b48-a98f-e52c3aecc636">
```zsh
git clone https://github.com/Shuri-Honda-1101/todo-go.git
```

todo-goディレクトリが作成されるのでvscodeで開く
```zsh
cd todo-go
code .
```

#### 新しくファイルを作成する
1. VScode上で新しく`readme.md`ファイルを作成する
2. 適当に文字列を追加し、保存する

#### ステージング
(以下の説明は初学者向けに雰囲気を掴むための説明)
最初はgitはゲームのセーブデータみたいなものだと思ってくれれば良い。
セーブポイントを作成しておけば、先に進んでしまった後もそのセーブデータに戻れる。
今の段階ではセーブポイントが作成されていないので、セーブポイントを作成してあげる必要がある(= コミット)
ステージングとは、変更したファイルのうち、何をセーブ対象とするかを決定するものだと思って欲しい。

ステージングは`git add <ファイル名>`というコマンドで行う
今は変更したファイルを全てステージング対象としたいため、`.`で現在のディレクトリ以下の全てのファイルを指定できる。

```zsh
# 現在の状態を確認する
git status
# ステージングに上がっていないファイルが一覧で見れる(ステージングになっていないファイルは赤字で表示されている)

# ステージング作業
# todo-goディレクトリで行う
git add .

# 再度状態を確認する
git status
# ステージング状態になったファイルが緑色で表示される
```

#### コミット
前述の通り、セーブポイントを作る作業を行う。
下記のコマンドで実行できる
```zsh
git commit -m <作業した内容を書く>
```
`-m`はコミットメッセージを設定するオプション。
今回であれば「readmeを追加した」が作業内容となるため、その内容を書けば良い。
(今回は日本語でも英語でもOK。実際に業務で使用する際は、プロジェクトでルールが決まっていることが多い)
```zsh
git commit -m "add readme"
```

ログを確認してみる
```zsh
git log
```

add readmeという名前のコミットが追加されていることが分かる。

#### プッシュ
現在の状態では作業者のPC上でしかセーブポイントの作成が反映されていない。
githubを利用するようなチーム開発では、他のメンバーがそのセーブポイントを取り込めるようにオンライン上にあげる必要がある。
この作業をプッシュと呼ぶ。
以下のコマンドでプッシュができる
```zsh
git push origin <ブランチ名>
```

今回はメインブランチにそのままpushして良いこととする。
(ブランチの説明は次回以降のタスクで説明する)
`git push`だけを行うと、そのリポジトリのメインブランチにpushができる。
そのため、以下のコマンドを入力すればOK
```zsh
git push
```

> (UserNameとパスワードを要求される場合)
> HTTPS通信だと、UserNameとパスワード(アクセストークン)を要求される。
> UserNameには自分のGitHubアカウント名を。
> パスワードには以下の流れで発行したアクセストークンを入力する。
> https://docs.github.com/ja/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
> 
> ssh接続や、GitHub CLIを設定していると上記の手順は必要ない。
> 興味があれば調べて設定すると便利。

リモートリポジトリ
https://github.com/Shuri-Honda-1101/todo-go
へアクセスする。
コミット履歴を見るとコミットが反映されていることが分かる。
https://github.com/Shuri-Honda-1101/todo-go/commits/main/

初コミットおめでとう！

## goのインストール
https://ritaiz.com/articles/steps-to-install-go-on-ubuntu
上記手順はgoのバージョンが1.21となっているため、適宜最新バージョンに変更して対応する。

## エディタにGo拡張機能を入れる
https://qiita.com/melty_go/items/c977ba594efcffc8b567

## Goの初期設定
serverディレクトリに移動する
```zsh
cd server
```

ライブラリのインストール
```zsh
go mod tidy
```

## サーバーを起動させる
```zsh
go run server.go
```

コマンドラインの表示が以下のようになり、サーバーが起動したことが確認できる
![Image](https://github.com/user-attachments/assets/ade22007-471a-46af-9f57-ffebd9865ef4)

ブラウザで`localhost:1323/`にアクセス
以下の画面が出ていればOK
![Image](https://github.com/user-attachments/assets/ea5c6e5f-1618-453b-8bab-3e81c09cf8fd)

### [課題]変更してみよう
画面に表示される文字列を自由に変更してみよう。

保存後は再度サーバーを起動させる
```zsh
# ctrl+Cで一度サーバーを落とす

# server起動
go run server.go
```

ブラウザで`localhost:1323/`にアクセスし、文字列が変わっていればOK

## gitをpullしてみる
最新のリモートリポジトリの変更を自分のPCに反映させよう

下記のコマンドを打つ
```zsh
git pull
```

```zsh
git log
```

下記のように`Author: Shuri Honda`のログが増えていれば
@Shuri-Honda-1101 
が作成したコミットが反映されている。
![Image](https://github.com/user-attachments/assets/389f5166-65be-499a-9138-68d4761464d9)

clientディレクトリが作成されていることが分かる
![Image](https://github.com/user-attachments/assets/3cb7d43f-9ba8-4e17-9323-0de31b42abcd)

## node.jsのインストール
node.jsはgoでの開発に直接関係はしないが、クライアント(フロント)側を動かす際に必要なためインストールする。
nodeはバージョン管理ツールを使ってインストールするのが一般的。

主要なバージョン管理ツール一覧
https://qiita.com/toya33/items/974c4d7b74489bda359d

今回はfnmを採用する。

### fnmのインストール
node.jsの公式サイトにインストール方法が書いてある
https://nodejs.org/en/download/package-manager
今回は最新版である22,Linux,fnmを選ぶ
```bash
# installs fnm (Fast Node Manager)
curl -fsSL https://fnm.vercel.app/install | bash

# activate fnm
source ~/.bashrc

# download and install Node.js
fnm use --install-if-missing 22

# verifies the right Node.js version is in the environment
node -v # should print `v22.5.1`

# verifies the right npm version is in the environment
npm -v # should print `10.8.2`
```

##  クライアントを起動する
clientディレクトリに移動する

```bash
# serverディレクトリにいると仮定する
# todo-goディレクトリに戻る
cd ../

# clientディレクトリに移動する
cd client
```

ライブラリをインストールする
```bash
npm install
```

サーバーからのレスポンスを表出させるコードを書いているので、サーバーも事前に起動させておく。
```bash
cd ../server
go run server.go
```

クライアントを起動させる
```
npm run dev
```

## MySQLをインストールする

verは8系を使用する。

https://cfd.life/column/ubuntumysql%E3%82%92%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97%E3%81%99%E3%82%8B/
上記を参考にする。

```bash
# MySQL の存在を確認
mysql --version
# 下記の表示が出るはず
# -bash: /usr/bin/mysql: そのようなファイルやディレクトリはありません

# Ubuntuを最新にアップデートしておく
sudo apt-get　Update

# MySQLのインストール
sudo apt-get mysql-server mysql-client

# インストールしただけでは基本的にシステムの稼働はされないため、コマンドから起動及び再起動後に自動的にシステムが起動するように設定する。
sudo systemctl start mysql.service 
sudo systemctl enable mysql.service

# mysqlの起動確認
sudo systemctl status mysql.service
# Activeの欄に緑色でactiveと書いてあればOK

# MySQL のバージョンを確認
mysql --version
# mysql  Ver 8.3.0 .....というような表示が出るはず

# パスワードの設定
# mysqlにログイン
sudo mysql
#  ログインすると下記の形で表示される
# mysql> 

#  パスワードを設定する
mysql> ALTER USER 'root'@'localhost' IDENTIFIED BY '新しいパスワード';
```

## データベースを作成する
解説記事として以下を参考にする
https://zenn.dev/wkb/books/node-tutorial/viewer/todo_04

todo-go用のデータベースを作成する

以下のコマンドを入力してmysqlにログインする
```bash
# mysqlにログイン
mysql -u root -p
# 前述で設定したパスワードを入力する
```

今回データベース名は`todo_go`とする。

```mysql
# データベースの作成
mysql> CREATE DATABASE todo_go;
# Query OK, 1 row affected (0.01 sec)

# データベースの一覧を表示するコマンド
mysql> SHOW DATABASES;
```

こんな感じに出力されるはず。
todo_goがあればOK
<img width="205" alt="スクリーンショット 2024-08-02 12 24 17" src="https://github.com/user-attachments/assets/4d19a705-5312-4ace-b239-5619ca3e6ea2">

MySQLでは実際にそのデータベースを操作する際、データベースを選択する必要がある。
これはUSEというコマンドで行える。
```mysql
# データベースの選択
mysql> USE todo_go;
# Database changed

# テーブル一覧を表示してみる
mysql> SHOW TABLES;
# Empty set (0.00 sec)
# まだテーブル作成前なのでEmptyとなる。
```

**Comment by Shuri-Honda-1101** [comment]
## 補足１
Gitの使い方を学びたいなら以下がオススメ
https://backlog.com/ja/git-tutorial/

**Comment by Shuri-Honda-1101** [comment]
## 補足２
その他おすすめの拡張機能

- VScodeの日本語化
  - Japanese Language Pack for Visual Studio Code
- インデントを見やすくする
  - indent-rainbow
- 全角スペースを検知する
  - zenkaku
- コードのフォーマット
  - Prettier - Code formatter
- Typo(誤植)検知
  -  Code Spell Checker

「VScode　拡張機能　オススメ」って調べるとたくさん記事が出てくるので、色々試してみると良い

**Comment by SakuraMii** [comment]
なぜ…

![Image](https://github.com/user-attachments/assets/595edf27-fcf9-4ed1-8c53-8c83b1d78d04)

**Comment by Shuri-Honda-1101** [comment]
> なぜ…

以下の記事を参照
https://qiita.com/tomlaw/items/df47acd61b70db3762e6
https://stackoverflow.com/questions/59806254/command-go-tools-install-not-found
-> GOPATH,GOROOTの設定がvscodeで反映されていない？

`go version`でバージョン情報は出るのでコマンドライン上でGoのパスは通っている

## 試したこと
.bashrcを更新する
```bash
export GOPATH=%USERPROFILE%¥go
export PATH=$PATH:$GOPATH/bin
```
```zsh
$ source ~/.bashrc
$ code .
```
-> 変化なし

```bash
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
```
に変更し再度同じ手順
-> 変化なし

```bash
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin
```
に変更し再度同じ手順
-> 変化なし

```bash
# 開発ディレクトリに変えてみる
export GOPATH=$HOME/dev
export PATH=$PATH:$GOROOT/bin
```
に変更し再度同じ手順
-> 変化なし

## 検討
1. 私の環境のgo envを見てみたが、
    ```zsh
    GOPATH='/Users/shurihonda/go'
    # 下はmacのためhomebrewで入れてるのでwindowsとは異なる
    GOROOT='/opt/homebrew/Cellar/go/1.22.5/libexec'
    ```
    なので、GOPATHはdevではなくgoで問題なさそうな気がする。
    
    私のパス設定
    ```zsh
    # Goの設定
    export PATH=$PATH:$(go env GOPATH)/bin
    ```
    上記に変えてみてもいいかも。(GOPATHの設定はしていなかったのでデフォルト設定)

2. とりあえず一旦PCを再起動してみる
3. 拡張機能のGoを一旦アンインストール -> VScodeを再起動 -> 再インストールしてみる。
4. 設定を確認する
    setting.jsonでgo.gopathやgo.gorootの設定を確認する
    (私の設定を確認したところ、特に指定をしていなかったので必須ではなさそう)
    
    setting.jsonの開き方
    - VScodeの設定ページを開く
    - 検索窓に「setting」と入力
    - setting.jsonで編集という項目が出てくるのでクリック


    > ちなみにvscodeのコマンドパレットでgo:current gopathコマンドを実行すると、設定されているgopathが確認できたりします。
    > (https://github.com/senkousya/startGoLangWithWindows)
    
    とのことなので、上記コマンドでパスを確認してみるといいかも。
    現在のバージョンでは自動でgopathが設定されるらしい。

**Comment by SakuraMii** [comment]
```$ code .```

VScode開いたときに下記表示されているのでPathが通っていない？

![Image](https://github.com/user-attachments/assets/3e38fdfb-d25a-47c5-beb7-806b42a7fd61)

PCの再起動しても変化なし

**Comment by Shuri-Honda-1101** [comment]
Gitのパスも通ってないなら、全体的にPC内部の何かが悪さして自動でPATHが設定されないようになってるのかも。
goの方もgitの方もsetting.jsonでPATH設定すれば直りそう。

https://ysko909.github.io/posts/fix-git-path-with-vscode/

https://qiita.com/momotaro98/items/7fbcad57a9d8488fe999

**Comment by Shuri-Honda-1101** [comment]
chatGPTに聞いた

> いまvscodeを開くとgitに関してもパスが通っていないと言われます。
> Ubuntu上ではコマンドを使えるのでpathが通っていると思います。
> 
> Windowsのユーザー環境変数にpathが
> %USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\miyaz\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\miyaz\AppData\Local\GitHubDesktop\bin
> のように設定されています。
> 
> これがVScodeの挙動に影響を与えている可能性はありますか？
> 
> Ubuntuで通っている環境変数を自動でVScodeが読み込めないのでしょうか？

VSCodeがWindows上でUbuntuの環境変数を自動で読み込むことはありません。WindowsとUbuntuは異なるシステムであり、それぞれの環境変数は独立しています。Windows上でVSCodeを使用する場合、Windowsの環境変数が適切に設定されている必要があります。

### Gitやその他のツールのパスが通っていない問題の解決方法

1. **Gitのパスを確認**:
   - Gitがインストールされているディレクトリ（通常は `C:\Program Files\Git\bin`）をWindowsの環境変数に追加してください。これにより、VSCodeからもGitコマンドが認識されるようになります。

2. **環境変数の設定**:
   - 「コントロールパネル」→「システムとセキュリティ」→「システム」→「システムの詳細設定」→「環境変数」から、`Path` 環境変数を選択し、「編集」をクリックします。
   - Gitのパス（例: `C:\Program Files\Git\bin`）を追加します。
   - VSCodeのパスも確認し、必要に応じて修正します。

3. **VSCodeの再起動**:
   - 環境変数を変更した後、VSCodeを完全に閉じてから再起動してください。これにより、新しい環境変数の設定が反映されます。

4. **WSLの利用**:
   - Ubuntuを利用している場合、Windows Subsystem for Linux (WSL) を使用している可能性があります。WSLを使用している場合、VSCodeには「Remote - WSL」拡張機能をインストールすることで、Ubuntu環境を直接利用することができます。
   - 「Remote - WSL」拡張機能をインストール後、VSCodeの左下の緑色の「><」アイコンをクリックして「Remote-WSL: New Window」を選択し、Ubuntu環境でVSCodeを開きます。

これらの手順を試しても問題が解決しない場合は、VSCodeの設定や環境変数の設定に誤りがないか再度確認してください。また、VSCodeのサポートフォーラムや公式ドキュメントを参照するのも良いでしょう。

-----

4番をやればUbuntuでパスが通っている＝VScodeでパスが通っている状態にできそう。
以下を試してみると良いかもしれない
https://qiita.com/zaburo/items/27b5b819fae2bde97a3b#windows%E3%81%A8%E3%81%AE%E9%80%A3%E6%90%BA%E3%81%AB%E3%82%88%E3%82%8B%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89vscode

**Comment by SakuraMii** [comment]
前に入れたPythonが邪魔してたかも？
![Image](https://github.com/user-attachments/assets/0b1b2c4e-d1e3-4c13-904e-6f1c8c441e02)

↑
違ったようだ

**Comment by SakuraMii** [comment]
VScodeの拡張機能でWSLが入ってないからUbuntではLinux環境でも、VScodeでLinuxになっていなかったため
WSLをインストールしたら解決した

**Comment by SakuraMii** [comment]
QiitaかZennで環境構築についての記事を書く（宿題）
2つとも見てみて自分のやりやすい方にして
#4

**Comment by SakuraMii** [comment]
SQLのインストールが下記コマンドでできなかったので

![Image](https://github.com/user-attachments/assets/64b05037-fade-4bf9-8a3f-97f057f98a36)

```
sudo apt-get install mysql-server
```
上記コマンドでインストール

![Image](https://github.com/user-attachments/assets/501c1e13-56af-48ed-a7dd-25e3054520ad)
バージョン確認もOK

MySQLにログインまでできたのだが、パスワードの設定で困った
任意の新しいパスワードを設定しようとすると
```
Query OK, 0 rows affected (0.01 sec)
```
これがででくるのだが、あっているのか確認したい…

**Comment by Shuri-Honda-1101** [comment]
> SQLのインストールが下記コマンドでできなかったので
> 上記コマンドでインストール

良いですね！！！

> これがででくるのだが、あっているのか確認したい…

合ってる！
Query OK = クエリが正常に実行された
0 rows affected = この操作が行データに直接影響を与えなかった(データをいじった訳ではなくパスワードを変更しただけなので)
0.01 sec = クエリの実行にかかった時間

その先のデータベースの作成の部分でログインをする工程があるから、そこでログイン出来たかをパスワードの設定が完了したかどうかの判断基準にしても良いです🙆

**Comment by SakuraMii** [comment]
```
sudo mysql -u root -p
```
コマンドで入れる（Windowsだから？）
rootユーザーでログインするのにsudoが必要
