### ISSUE TITLE
環境構築で得た知見を技術記事としてUPする

### ISSUE THREAD

**Issue by Shuri-Honda-1101** [Shuri-Honda-1101/todo-go#4]
# 概要
環境構築で得た知見を技術記事としてUPする。
使用するツールは以下から自由に選んで良い
[zenn](https://zenn.dev/)
[Qiita](https://qiita.com/)

# 目的
- 技術記事を書くことに慣れる
- アウトプットで知識を再整理する

# その他
最初なので詳しく書こうとする必要はない。
- 何が起こったのか
- 何をやったら解決したのか
- 何が原因だったと考えられるか

くらいでOK

こんな感じの軽めな記事でOK
https://zenn.dev/haru507/articles/49703c14da3656

飽くまでもアウトプットして記事を投稿するが目標

# 補足
@Shuri-Honda-1101 のZennページ
https://zenn.dev/danbo

**Comment by SakuraMii** [comment]
記事初公開
https://zenn.dev/000oishiigohan/articles/5905d840d5f59e

知らない用語とか調べながらやったけど間違ってたら指摘が欲しいです

**Comment by Shuri-Honda-1101** [comment]
> 1 .bashrcを更新する
> 
> export GOPATH=%USERPROFILE%¥go
> export PATH=$PATH:$GOPATH/bin
> 
> $ source ~/.bashrc
> $ code .
> 
> -> 変化なし
> 
> 2.Unix系のシステム（LinuxやMacOS）でGoの環境を設定するコードにしてみる
> 
> export GOPATH=$HOME/go
> export PATH=$PATH:$GOPATH/bin
> 
> に変更し再度同じ手順
> -> 変化なし
> 
> 3.Goの環境変数を設定
> 
> export GOPATH=$HOME/go
> export PATH=$PATH:$GOROOT/bin
> 
> に変更し再度同じ手順
> -> 変化なし
> 
> 4.開発ディレクトリに変えてみる
> 
> export GOPATH=$HOME/dev
> export PATH=$PATH:$GOROOT/bin
> 
> に変更し再度同じ手順
> -> 変化なし

.bashrcで明示的にGoのPATHを指定してみる。

1. GOPATHをUSERPROFILE変数下のgoディレクトリにしてみる
...省略

2.  GOPATHをHOME変数下のgoディレクトリにしてみる
...省略

3. PATHをGOPATHではなくGOROOT下にしてみる
...省略

4. GOPATHをdevディレクトリに変えてみる(自分の環境ではdevディレクトリを開発用ディレクトリとして扱っているため)
 ...省略


正確に書くならこんな感じかも！


> Ubuntu上ではコマンドを使えるのでpathは通っているが、VScodeでpathが通っていない模様
> chatGPTに聞いたところ、
> 
> 『Gitやその他のツールのパスが通っていない問題の解決方法』を教えてくれた。
> Ubuntuを利用している場合、Windows Subsystem for Linux (WSL) を使用している可能性があります。WSLを使用している場合、VSCodeには「Remote - WSL」拡張機能をインストールすることで、Ubuntu環境を直接利用することができます。
> 「Remote - WSL」拡張機能をインストール後、VSCodeの左下の緑色の「><」アイコンをクリックして「Remote-WSL: New Window」を選択し、Ubuntu環境でVSCodeを開きます。


『Gitやその他のツールのパスが通っていない問題の解決方法』を教えてくれた。
↑の部分もChatGPTの回答部分に入っちゃってるのが誤植かな。

**Comment by SakuraMii** [comment]
> > 1 .bashrcを更新する
> > export GOPATH=%USERPROFILE%¥go
> > export PATH=$PATH:$GOPATH/bin
> > $ source ~/.bashrc
> > $ code .
> > -> 変化なし
> > 2.Unix系のシステム（LinuxやMacOS）でGoの環境を設定するコードにしてみる
> > export GOPATH=$HOME/go
> > export PATH=$PATH:$GOPATH/bin
> > に変更し再度同じ手順
> > -> 変化なし
> > 3.Goの環境変数を設定
> > export GOPATH=$HOME/go
> > export PATH=$PATH:$GOROOT/bin
> > に変更し再度同じ手順
> > -> 変化なし
> > 4.開発ディレクトリに変えてみる
> > export GOPATH=$HOME/dev
> > export PATH=$PATH:$GOROOT/bin
> > に変更し再度同じ手順
> > -> 変化なし
> 
> .bashrcで明示的にGoのPATHを指定してみる。
> 
> 1. GOPATHをUSERPROFILE変数下のgoディレクトリにしてみる
>    ...省略
> 2. GOPATHをHOME変数下のgoディレクトリにしてみる
>    ...省略
> 3. PATHをGOPATHではなくGOROOT下にしてみる
>    ...省略
> 4. GOPATHをdevディレクトリに変えてみる(自分の環境ではdevディレクトリを開発用ディレクトリとして扱っているため)
>    ...省略
> 
> 正確に書くならこんな感じかも！
> 
> > Ubuntu上ではコマンドを使えるのでpathは通っているが、VScodeでpathが通っていない模様
> > chatGPTに聞いたところ、
> > 『Gitやその他のツールのパスが通っていない問題の解決方法』を教えてくれた。
> > Ubuntuを利用している場合、Windows Subsystem for Linux (WSL) を使用している可能性があります。WSLを使用している場合、VSCodeには「Remote - WSL」拡張機能をインストールすることで、Ubuntu環境を直接利用することができます。
> > 「Remote - WSL」拡張機能をインストール後、VSCodeの左下の緑色の「><」アイコンをクリックして「Remote-WSL: New Window」を選択し、Ubuntu環境でVSCodeを開きます。
> 
> 『Gitやその他のツールのパスが通っていない問題の解決方法』を教えてくれた。 ↑の部分もChatGPTの回答部分に入っちゃってるのが誤植かな。

**Comment by SakuraMii** [comment]
https://github.com/Shuri-Honda-1101/todo-go/issues/4#issuecomment-2267413955

誤植と説明文修正完了！
引用の不要な部分巻き込むのはよくやるので気を付けてね私さん
