### ISSUE TITLE
tasksテーブルを作成する

### ISSUE THREAD

**Issue by Shuri-Honda-1101** [Shuri-Honda-1101/todo-go#5]
# 概要

新しくブランチを切って、MySQLでTASKテーブルを作成するSQLを作成し、プルリクエストを出す。
また、フロントエンドを起動し、作成するアプリの挙動を確かめる

# 目的

- GitHub flowに慣れる
- ブランチを切れるようになる
- プルリクエストを作成できるようになる
- マイグレーションファイルを作成できるようになる
- マイグレーションを行い、動作確認を行う手順を学ぶ
- 作成するアプリケーションのゴールを理解する

# タスク
- [x] クライアントサイドの挙動を確認する
- [x] ブランチを切る
- [x] mysql.confを設定する
- [x] マイグレーションを試してみる
- [x] TASKテーブルを作成するSQLを書く
- [x] データを挿入してみよう
- [x] プルリクエストを作成する

# 具体的な手順

## 事前準備
最新のmainブランチをpullしてくる。
やり方は #1 で行った内容を参照すること。

## クライアントサイドの挙動を確認する

クライアントを起動させる。
手順がわからない場合、 #1 を参照する。

<img src="https://github.com/user-attachments/assets/fa2defbd-29ef-4f25-866a-9a07aa3386e6" width="400px">

↑のページが表示されればOK

タスクの追加や削除を一通り試した後、リロードを行ってみよう。
リロードを行った時にタスクが消えてしまうことが分かると思う。
これは、データベースに保存しておらず、データを永続化できていないため。
今アプリケーションでのサーバー側の役割は
「クライアント側で作成したタスクを保存する処理を行うこと」
と認識してほしい。

### 事前に読んでおこう
作業を行う前に、作業用のブランチを切る必要がある。
https://backlog.com/ja/git-tutorial/stepup/01/
上記の講座を読んでおく。

※ `master`ブランチ = `main`ブランチ
※ 昔は`master`というブランチ名だったが、奴隷制度を彷彿とさせるとかなんとかで名前が変わった。

ブランチ運用には３つの大きな流派がある。
https://qiita.com/onishi_820/items/d98c61e0faa67f417829
今回はGitHub flowを採用する。

### ブランチを切ってみる。
以下のコマンドでブランチを作成する。
尚、ブランチ名の命名規則は[wiki](https://github.com/Shuri-Honda-1101/todo-go/wiki/%E9%96%8B%E7%99%BA%E3%83%AB%E3%83%BC%E3%83%AB#%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E5%90%8D)を参照する。

```zsh
# todo_goディレクトリ配下で行う
$ git checkout -b [ブランチ名]
```

※ -bというフラグをつけることで、ブランチを切った後、自動でそのブランチに移動する。

### 今いるブランチを確認する

```zsh
$ git branch
```
下記のように表示されればOK。
![Image](https://github.com/user-attachments/assets/2713b618-1141-4724-883e-4eeb2963fcf7)
現在のブランチは緑色で表示される。

また、VScodeを使っている場合、左下に現在のブランチが表示される。

![Image](https://github.com/user-attachments/assets/fe94692c-c331-4518-8d8a-58b98a5f8839)

## mysql.confを設定する

SQLを書くための事前準備としてmysqlのユーザー名とパスワードを設定しておく。
ユーザー名やパスワードは各々の環境で異なるため、confファイルで設定を行っておくことで、共通のコマンドによる自動化が行えるようになる。

※ どんな自動化を行っているのか知りたい場合は、 #10 のプルリクを確認する。
※ (発展的な内容になるので現段階で理解はしなくても良い。質問は歓迎。)

`mysql.conf_example`という設定ファイルの雛形を作成しているので、コピーして名前を変更する。

```zsh
# serverディレクトリで行う
$ cp mysql.conf_example mysql.conf
```

`mysql.conf`というファイルがグレーの色で表示されていることが分かると思う。
グレーになっているのは、gitで履歴を追わない設定を`.gitignore`で行っているため。
(パスワードなど機密情報にあたることはGitHub上にpushしてしまうと漏洩リスクがあるため、基本的にignodeする。)

`mysql.conf`を開き、ユーザー名とパスワードを書いていく。
環境構築で提示した流れのまま設定を行っていた場合、ユーザー名はrootで問題ない。
(別途設定をした場合は、各々が設定したユーザー名を書く)
```conf
[client]
user=root
password=[ここに設定したパスワードを入力する]
```

## マイグレーションを試してみる

事前に設定しているマイグレーションファイルがあるので、マイグレーションを試してみる。
マイグレーションとは -> https://qiita.com/to3izo/items/7b8d44021cb386de2ef7#%E3%83%9E%E3%82%A4%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%A8%E3%81%AF

ざっくりいうと、マイグレーション = テーブルを作成するなどの処理をDBに適用すること。

今回はmakefileにコマンドを設定しているため、以下のコマンドでマイグレーションを行うことができる。

```zsh
# serverディレクトリ
$ make migrate
```

![Image](https://github.com/user-attachments/assets/909bb088-dfa8-4d13-8261-fcd5fd07a7e7)
↑の表示が出ればOK

<details><summary>permission deniedが出る場合</summary>
<p>
ファイルの実行権限がない場合、permission deniedというエラーが発生する。
`chmod`というコマンドで権限を変更することができる。

```zsh
# serverディレクトリ
$ chmod 755 script/migrate.sh
```

権限の設定について -> https://qiita.com/mokio/items/daa99f969a66771b80f7
</p>
</details> 

実際にテーブルが作成されたかどうかを確認してみよう。
確認の手順は #1 を参照する。

![Image](https://github.com/user-attachments/assets/cb029943-5ae7-43ff-9bb5-33e4696078bc)

↑のようにschema_migrationsというテーブルが作成されたことが確認できる。

## TASKテーブルを作成するSQLを書く

いよいよSQLを書いていこう。

作成するテーブルの定義は以下の通り。
https://github.com/Shuri-Honda-1101/todo-go/wiki/DB%E5%AE%9A%E7%BE%A9#tasks

`server/sql/migrations`にSQLファイルを作成する。
ファイルの命名規則は[wiki](https://github.com/Shuri-Honda-1101/todo-go/wiki/%E9%96%8B%E7%99%BA%E3%83%AB%E3%83%BC%E3%83%AB#%E3%82%B9%E3%82%AD%E3%83%BC%E3%83%9E%E5%AE%9A%E7%BE%A9%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D)を参照

ファイルの内容は自分で考えてみよう！

SQLファイルを作成し、SQL文を書いたら、マイグレーションを行う。
マイグレーション後、以下のコマンドでテーブル定義の確認を行う。

```sql
mysql> SHOW TABLES;
mysql> SHOW COLUMNS FROM tasks;
```

以下が表示されていればOK。

![Image](https://github.com/user-attachments/assets/d34d0ea5-a251-47e4-abfc-baca44f97d9e)

![Image](https://github.com/user-attachments/assets/d71259b0-1236-4c47-b842-15bb65d557e6)

<details><summary>失敗したからリセットしたい時</summary>
<p>
以下のリセット用のスクリプトを用意している

```zsh
$ make db_reset
```

![Image](https://github.com/user-attachments/assets/8ff2c1ff-04dd-4729-a766-79a84aa42537)
</p>
</details> 

## データを挿入してみよう

実際にデータを挿入してみよう。
以下の設定でtasksにデータの挿入処理を行う。

- text: 新しいタスク
- completed_at: null
- deleted_at: null

```sql
mysql> [内容は自分で考えてみよう！]
```

以下のコマンドで結果を確認する

```sql
mysql> SELECT * FROM tasks;
```

![Image](https://github.com/user-attachments/assets/b40d9720-8e71-40cb-951b-7b8bc3ae29ae)

上記のようになっていればOK

データを挿入した際のコマンドと結果を今Issueのコメントに貼っておくこと。

## プルリクエストを作成する。

プルリクエストを作成してレビュー -> マージの流れを体験する。

まず、現在のブランチが`main`ブランチではなく、`feature/xxx/xxxxx`というブランチになっていることを確認する。(重要)
確認ができたら、ステージング -> コミット -> プッシュを行う。
コミット名の命名規則は[wiki](https://github.com/Shuri-Honda-1101/todo-go/wiki/%E9%96%8B%E7%99%BA%E3%83%AB%E3%83%BC%E3%83%AB#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E5%90%8D)を参照する。

```zsh
# todo_goディレクトリ、またはserverディレクトリ
# 最初にmainブランチの変更を取り込んでおく
$ git pull origin main
# ステージング
$ git add .
# コミット
$ git commit -m [コミットメッセージ]
# プッシュ
$ git push origin HEAD
```

現在のブランチをちゃんと確認しなかった場合、mainブランチに直接pushとなってしまうことがある。
mainブランチ直pushは大罪なので気をつけよう。

pushが完了したら、GithubのリポジトリのTOPページを見ると以下のような画面が出ると思う。
![Image](https://github.com/user-attachments/assets/829bc3a7-022d-4726-a545-50e43ef5764a)

Compare&pull requestのボタンを押し、プルリクを作成する。
テンプレートが設定されているので、

タイトル：作業した内容
本文：テンプレートに沿って内容を書く

という形で編集する。
#12 , #10 あたりを参考にする。(あまり参考にならないかもしれない)

reviewerに @Shuri-Honda-1101 を選択
assignは自分自身を選択する。

<img src="https://github.com/user-attachments/assets/bc904f2f-c26d-4e2f-9054-18f722bec5d1" width="400px"></br>

<img src="https://github.com/user-attachments/assets/cf6be78f-2c8b-4ccf-9c92-3e95acef6496" width="400px">  <br>

全て完了したら
Create Pull Request
ボタンを押す

**Comment by SakuraMii** [comment]
makeコマンドはインストールが必要っぽい

![Image](https://github.com/user-attachments/assets/2457303e-5fad-45ed-8595-d54a3253f1a2)

```
sudo apt update
sudo apt install build-essential
```
上記コマンドでインストール

**Comment by SakuraMii** [comment]
今日中にこれやります
https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql-ja

mysql.conf
の再設定

**Comment by SakuraMii** [comment]
https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql-ja
上記記事の通り再設定完了

が。
rootのときと変わらないエラー

![Image](https://github.com/user-attachments/assets/bbcb10de-afa4-4d9d-bfa0-a05b71d7998c)

一応
`sudo`を頭に入れてやってみたらできた

![Image](https://github.com/user-attachments/assets/3fa6907e-cb23-497f-963e-81d473a829d4)

ドウシテ…になってしまったので記事を調べてみたが「Windowsにsudoが実装できるぞ～！」って記事は見つけたが明確になぜかの記載がなかったので、「MacとWindowsでのsudoの使い方の違いについて」ChatGPTに聞きました。

> WindowsとMacではsudoの使い方や権限管理の方法に違いがあります。以下にそれぞれの違いを説明します。
Windowsの場合
特権ユーザー
Windowsでは、管理者権限（Administrator）のユーザーが特権操作を行うための役割を担います。通常、管理者権限を持つユーザーアカウントを使用している場合、特定の操作を行う際に権限の昇格が求められることがあります。
管理者として実行
Windowsでは、sudoコマンドの代わりに、特権が必要な操作を行うためには、以下のように操作します。
コマンドプロンプト（cmd）またはPowerShellを管理者として実行:
スタートメニューで「cmd」または「PowerShell」を検索し、右クリックして「管理者として実行」を選択します。
管理者としてコマンドプロンプトやPowerShellを実行すると、sudoなしで管理者権限を必要とする操作を実行できます。

> Macの場合
特権ユーザー
macOSでは、sudoコマンドを使用して一時的に特権ユーザー（root）として操作を行うことが一般的です。これはUnix系システム（Linux、macOSなど）の共通の方法です。
Windows: 管理者としてコマンドプロンプトやPowerShellを実行することで特権操作を行います。
Mac: sudoコマンドを使用して一時的に特権操作を行います。
操作方法:
Windows: GUIから「管理者として実行」を選択することで簡単に権限を昇格できます。
Mac: ターミナルでsudoコマンドを使って権限を昇格します。
まとめ
WindowsとMacでは特権操作を行う方法が異なりますが、それぞれの環境で特権ユーザーとして操作を行う方法を理解することが重要です。Windowsでは「管理者として実行」を使い、Macではsudoコマンドを使用することが一般的です。これにより、システム管理やソフトウェアのインストールなどの操作を適切に実行できます。

たしかにWindowsでなにか設定を変えようとしたときとか、キッティングするときにやたら「管理者として実行」を求められていたのでつまりそういうこと…？
ここらへんは明日聞きたい

**Comment by SakuraMii** [comment]
`GRANT ALL PRIVILEGES ON * . * TO 'newuser'@'localhost';`

で権限の付与をしていなかった

or

`FLUSH PRIVILEGES;`

権限の付与はしたけどリロードをしていなかったかのどっちか

解決

**Comment by SakuraMii** [comment]
挿入したコマンド
~~~
mysql> INSERT INTO tasks(text) VALUES ('ごみ捨て');
~~~

結果

![Image](https://github.com/user-attachments/assets/fe93357c-f5d4-4496-946e-07d5ba13ad44)

**Comment by SakuraMii** [comment]
**やらかし一覧**

・コミット名に不要なカッコ

![Image](https://github.com/user-attachments/assets/f4c5b1c5-5f1f-4948-9e7a-c6d09d413416)

->コミットの修正
https://zenn.dev/suginoki45/articles/c94b05d1155cda
->Vimに閉じ込められたので
https://qiita.com/aiandrox/items/ecc2b872841126db5460

・よくわからないブランチ名を付ける

![Image](https://github.com/user-attachments/assets/065ab913-2256-45f9-8a30-dd2872de17b4)

リネームの ->
https://qiita.com/suin/items/96c110b218d919168d64

※リネームしたら新しくまたプルリクエスト再作成
※今回のプルリクを引き継ぐことはできない


・不要なものまでステージングした
![Image](https://github.com/user-attachments/assets/bdf8b2f6-4db4-45cb-8e17-cce63dd6d0c6)
-> `git restore --staged server.go`　今回不要だったserver.goを削除

懲りずにコミットメッセージは間違えるわ、ブランチの名前はわけわかんないわなので気を付けてください。
100回練習して未来の私

**Comment by Shuri-Honda-1101** [comment]
@SakuraMii 

#24 のPRのレビュー完了 -> approveしました！

| approve前 | approve後 |
|--------|--------|
| <img width="928" alt="スクリーンショット 2024-08-13 22 10 03" src="https://github.com/user-attachments/assets/c5f469ca-6994-424e-9429-ecee333c20bd"> | <img width="1034" alt="スクリーンショット 2024-08-13 22 09 24" src="https://github.com/user-attachments/assets/2dca6221-bc24-4663-bafa-b244f31a7d1c"> | 

こんな感じで、表示が変わってると思う！
緑色のボタンを押せば、mainブランチにマージができます！(mainブランチに変更が反映される)
基本的にタスクの完了はマージするまでなので、approveをもらったらマージしましょう！
